version: "3.9"

services:
   db:
    container_name: fastify_drizzle_postgres_db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./data:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
